# Generated by Django 5.2.3 on 2025-07-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
