# Generated by Django 5.2.3 on 2025-07-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_description_en_story_description_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
