# Generated by Django 5.2.3 on 2025-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_page_content_en_page_content_fa_page_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='text_fa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
