# Generated by Django 5.2.3 on 2025-07-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_option_text_en_option_text_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
