# Generated by Django 5.2.3 on 2025-07-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'User Progress', 'verbose_name_plural': 'User Progresses'},
        ),
    ]
