# Generated by Django 5.2.3 on 2025-07-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_option_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='story_backgrounds/'),
        ),
    ]
